version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data_storage
    env_file:
      - .env

  notes:
    container_name: notes
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata: